- name: Ensure env is explicitly set
  fail:
    msg: "env variable must be explicitly set (test/prod)"
  when: env == "dev"

- name: Generate timestamp
  set_fact:
    backup_file: "/tmp/dr_app_{{ ansible_date_time.iso8601_basic }}.sql"

- name: Take MySQL backup
  shell: mysqldump -u {{ db_user }} -p{{ lookup('env','DB_PASSWORD') }} {{ db_name }} > {{ backup_file }}

- debug:
    msg: "Using buckets {{ s3_bucket }} and {{ vault_bucket }}"

# Upload to NORMAL S3 (uses AWX credential)
- name: Upload backup to normal S3
  shell: aws s3 cp {{ backup_file }} s3://{{ s3_bucket }}/

# Upload to SECURE S3 (separate credential)
- name: Upload backup to secure S3
  shell: aws s3 cp {{ backup_file }} s3://{{ vault_bucket }}/
  environment:
    AWS_ACCESS_KEY_ID: "{{ lookup('env', 'AWS_VAULT_ACCESS_KEY') }}"
    AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_VAULT_SECRET_KEY') }}"
    AWS_DEFAULT_REGION: "{{ aws_region }}"

#- name: Cleanup local backup
#  file:
#    path: "{{ backup_file }}"
#    state: absent
