- name: Remove default Apache index.html
  file:
    path: /var/www/html/index.html
    state: absent

- name: Deploy index.php
  copy:
    src: index.php
    dest: /var/www/html/index.php
    mode: '0644'

- name: Set correct permissions
  file:
    path: /var/www/html
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
