- name: Close ServiceNow Incident
  hosts: localhost
  gather_facts: no

  vars:
    snow_instance: "https://dev290059.service-now.com"

  tasks:

    - name: Validate required variables
      fail:
        msg: "Missing incident_number or incident_sys_id"
      when:
        - incident_number is not defined or incident_number | length == 0
        - incident_sys_id is not defined or incident_sys_id | length == 0

    - name: Print incident details
      debug:
        msg: "Closing incident {{ incident_number }}"

    - name: Close incident in ServiceNow
      uri:
        url: "{{ snow_instance }}/api/now/table/incident/{{ incident_sys_id }}"
        method: PATCH
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        force_basic_auth: yes
        headers:
          Content-Type: "application/json"
          Accept: "application/json"
        body_format: json
        body:
          state: "7"
          close_code: "Solved (Permanently)"
          close_notes: "DR completed successfully via AWX"
          resolution_code: "Solved (Permanently)"
        status_code: [200, 201]
        return_content: yes
      register: result

    - name: Show ServiceNow response
      debug:
        var: result.json

    - name: Confirm closure
      debug:
        msg: "Incident {{ incident_number }} closed successfully"
      when: result.status in [200, 201]
