- name: DR Restore - Web + DB
  hosts: all
  gather_facts: no
  become: yes

  tasks:

    - name: Add dynamic host
      add_host:
        name: "{{ target_host }}"
        groups: dr_dynamic
        ansible_user: ubuntu

- name: Run restore on dynamic host
  hosts: dr_dynamic
  become: yes

  roles:
    - app_restore
