name: DR Prod Pipeline

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Ansible and Lint
        run: |
          pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Ansible Lint (GitHub friendly)
        run: |
          echo "---- ANSIBLE LINT ----"

          ansible-lint -p | while IFS= read -r line; do
            echo "::error::$line"
          done

          ansible-lint

      - name: Syntax Check All Playbooks
        run: |
          echo "---- ANSIBLE SYNTAX CHECK ----"
          ansible-playbook playbooks/backup.yml --syntax-check
          ansible-playbook playbooks/restore.yml --syntax-check
          ansible-playbook playbooks/health.yml --syntax-check

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    environment: production

    steps:
      - name: Trigger AWX PROD Workflow
        run: |
          echo "---- TRIGGERING AWX PROD DR ----"

          curl -k -X POST "${{ secrets.AWX_URL }}/api/v2/workflow_job_templates/21/launch/" \
          -H "Authorization: Bearer ${{ secrets.AWX_TOKEN }}" \
          -H "Content-Type: application/json"