name: DR Prod Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Trigger AWX PROD Workflow
        run: |
          curl -k -X POST https://attempt-headphone-qualify.ngrok-free.dev/api/v2/workflow_job_templates/21/launch/ \
          -H "Authorization: Bearer ${{ secrets.AWX_TOKEN }}" \
          -H "Content-Type: application/json"